- AnaliseProjeto/AjudAki.mdj
- Adiciona herança.
- Atualiza cardinalidades.
- Atualiza casos de uso.
- Atualiza o DER.
Close #1
> Revisa e atualiza o modelo de análise de projeto

- AnaliseProjeto/AjudAki.mdj
> Implementa diagrama de pacotes no modelo de análise

- AnaliseProjeto/AjudAki.mdj
> Atualiza métodos de persistência no diagrama de interação

- README.md
> Atualiza o README.md do projeto

- AnaliseProjeto/AjudAki.mdj
> Ajusta DER com o Dicionário de Dados

- Codigo/AjudAkiWeb/AjudAkiWeb/AjudAkiWeb.csproj
- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/AgendaController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/AreaAtuacaoController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/AssinaturaController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/AvaliacaoController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/ClienteController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/ProfissionalController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/ServicoController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/TipoServicoController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Agenda/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Agenda/Delete.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Agenda/Details.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Agenda/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Agenda/Index.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/AreaAtuacao/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/AreaAtuacao/Delete.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/AreaAtuacao/Details.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/AreaAtuacao/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/AreaAtuacao/Index.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Assinatura/Index.cshtml
Criação dos controladores e algumas views
#95
> Atualização do Projeto WEB

- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Assinatura/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Assinatura/Delete.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Assinatura/Details.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Assinatura/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Avaliacao/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Avaliacao/Delete.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Avaliacao/Details.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Avaliacao/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Avaliacao/Index.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Cliente/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Cliente/Delete.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Cliente/Details.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Cliente/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Cliente/Index.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Profissional/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Profissional/Delete.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Profissional/Details.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Profissional/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Profissional/Index.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Servico/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Servico/Delete.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Servico/Details.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Servico/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Servico/Index.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/TipoServico/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/TipoServico/Delete.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/TipoServico/Details.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/TipoServico/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/TipoServico/Index.cshtml
Finalizado as views restantes  #Close 108
> Atualizado e finalizado as views

- Codigo/AjudAkiWeb/Core/Areaatuacao.cs
- Codigo/AjudAkiWeb/Core/Core.csproj
- Codigo/AjudAkiWeb/Core/Service/IAreaAtuacaoService.cs
- Codigo/AjudAkiWeb/Service/AreaAtuacaoService.cs
> Implementar CSU10 - Manter áreas de atuação

- Codigo/AjudAkiWeb/Core/Assinatura.cs
- Codigo/AjudAkiWeb/Core/Service/IAssinaturaService.cs
- Codigo/AjudAkiWeb/Service/AssinaturaService.cs
> Implementação do IService e Service.

- Codigo/AjudAkiWeb/Core/Pessoa.cs
- Codigo/AjudAkiWeb/Core/Service/IClienteService.cs
- Codigo/AjudAkiWeb/Service/ClienteService.cs
- Cria a interface IClienteService.
- Cria o Service ClienteService.
- Ajusta atributo Id do tipo int para uint para fins de conversão, pois o Create do IClienteService foi usado o tipo uint.
Close #93
> Implementa caso de uso ManterCliente (1/3)

- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Home/Index.cshtml
Faltando as imagens que serão adicionadas futuramente!
> Implementação do HTML da tela inicial

- Codigo/AjudAkiWeb/AjudAkiWeb/Mappers/ClienteProfile.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/ClienteViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/ProfissionalViewModel.cs
- Codigo/AjudAkiWeb/Core/Service/IClienteService.cs
- Codigo/AjudAkiWeb/Service/ClienteService.cs
- Ajusta nomenclatura de Id no ClienteService e IClienteService.
- Retira o default do profissionalViewModel.
Close #101
> Implementa ViewModel e Mappers do Manter Cliente

- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/ClienteController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Mappers/ClienteProfile.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/AssinaturaViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/ClienteViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/OfertarServicoViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/ProfissionalViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Program.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Cliente/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Cliente/Delete.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Cliente/Details.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Cliente/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Cliente/Index.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Shared/_Layout.cshtml
- Codigo/AjudAkiWeb/Service/ClienteService.cs
- Implementa ClienteController, Views do ClienteController
- Implementa no program o manterCliente.
- Retira partes do projeto que deram erro:
- Retira uma "}" a mais do arquivo AssinaturaViewModel.
- Deixa a string de nome nulavel em OfertarServicoViewModel.
- Retira o IdTipoServico e o IdProfissional.
- Deixa a AssinaturaViewModel nulavel em ProfissionalViewModel.
- Renomeia ClienteModel para ClienteViewModel em Models.
- Adiciona Mappers ao Program.
- Retira libs desnecessárias no ClienteService.
Close #97
> Implementa o caso de uso Manter Cliente(3/3)

- Codigo/AjudAkiWeb/AjudAkiWeb/Mappers/AreaAtuacaoProfile.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/AreaAtuacaoViewModel.cs
> Implementação da viewModel e Mappers

- Codigo/AjudAkiWeb/AjudAkiWeb.sln
- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/AreaAtuacaoController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/ServicoController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Program.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/AreaAtuacao/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/AreaAtuacao/Delete.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/AreaAtuacao/Details.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/AreaAtuacao/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/AreaAtuacao/Index.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Shared/_Layout.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/appsettings.json
- Codigo/AjudAkiWeb/AjudAkiWebTests/AjudAkiWebTests.csproj
- Codigo/AjudAkiWeb/AjudAkiWebTests/AreaAtuacaoControllerTests.cs
- Codigo/AjudAkiWeb/Core/Service/IAreaAtuacaoService.cs
- Codigo/AjudAkiWeb/Service/AreaAtuacaoService.cs
- Codigo/AjudAkiWeb/ServiceTests/AreaAtuacaoServiceTests.cs
- Codigo/AjudAkiWeb/ServiceTests/ServiceTests.csproj
Adição AreaAtuacaoController.cs e Views correspondentes
close #124
> Criação dos Projetos de Testes

- Codigo/AjudAkiWeb/AjudAkiWebTests/AjudAkiWebTests.csproj
- Codigo/AjudAkiWeb/AjudAkiWebTests/Controllers/ClienteControllerTests.cs
- Codigo/AjudAkiWeb/ServiceTests/ClienteServiceTests.cs
- Codigo/AjudAkiWeb/ServiceTests/ServiceTests.csproj
- Remove um arquivo morto do starUML.
Close #126
> Implementa testes do Manter Ciente

- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/ProfissionalController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Mappers/ProfissionalProfile.cs
- Codigo/AjudAkiWeb/AjudAkiWebTests/AjudAkiWebTests.csproj
- Codigo/AjudAkiWeb/AjudAkiWebTests/Controllers/ProfissionalControllerTests.cs
- Codigo/AjudAkiWeb/ServiceTests/ProfissionalServiceTests.cs
- Codigo/AjudAkiWeb/ServiceTests/ServiceTests.csproj
> Criar testes para o Manter Profissional

- Codigo/AjudAkiWeb/AjudAkiWeb/Mappers/AgendaProfile.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/AgendaViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/ClienteViewModel.cs
- Codigo/AjudAkiWeb/Core/Service/IAgendaService.cs
- Codigo/AjudAkiWeb/Service/AgendaService.cs
- Codigo/AjudAkiWeb/Service/AreaAtuacaoService.cs
- Codigo/AjudAkiWeb/Service/AvaliarService.cs
- Codigo/AjudAkiWeb/Service/ProfissionalService.cs
Implementação da interface, service, mappers e ViewModel
> Implementação do manter Agenda (1/3 e 2/3)

- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/AgendaController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/AreaAtuacaoController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/AgendaViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Program.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Agenda/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Agenda/Delete.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Agenda/Details.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Agenda/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Agenda/Index.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Shared/_Layout.cshtml
> Implementar CSU006 - Manter agenda (3/3)

- Codigo/AjudAkiWeb/AjudAkiWeb/Mappers/ContratacaoProfile.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/AssinaturaViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/ContratacaoViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/ProfissionalViewModel.cs
- Ajusta espaçamento no ProfissionalViewModel
> Implementa CSU01 - Contratar Serviço - (2/3)

- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/ContratacaoController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/ServicoController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/ContratacaoViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/ServicoViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/TipoServicoViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Program.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Contratacao/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Contratacao/Delete.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Contratacao/Details.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Contratacao/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Contratacao/Index.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Servico/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Servico/Delete.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Servico/Details.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Servico/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Servico/Index.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Shared/_Layout.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/appsettings.json
- Codigo/AjudAkiWeb/Core/AjudakiContext.cs
- Codigo/AjudAkiWeb/Core/Service/IContratacaoService.cs
- Codigo/AjudAkiWeb/Service/ContratacaoService.cs
- Ajusta views do SolicitaçãoServiço:
- Foreign keys faltando, implementação estava incompleta.
- Ajusta TipoServicoViewModel que estava também faltando uma foreign key.
Close #106
> Implementa CSU01 - Contratar Serviço - (3/3)

- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/AvaliarController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Mappers/AvaliarProfile.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/AvaliarViewModel.cs
- Codigo/AjudAkiWeb/Core/Service/IAvaliarService.cs
Caso de Uso Avaliar Profissional:
Implementar ViewModel
Implementar Mappers
Implementar Controladores
close #180
> Implementar CSU012 - Avaliar Profissional (2/3)

- Codigo/AjudAkiWeb/AjudAkiWeb/Mappers/PagarAssinaturaProfile.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/PagarAssinaturaViewModel.cs
- Codigo/AjudAkiWeb/Core/Dto/PagarAssinaturaDTO.cs
- Codigo/AjudAkiWeb/Core/Service/IPagarAssinaturaService.cs
- Codigo/AjudAkiWeb/Service/PagarAssinaturaService.cs
- Implementação do PagarAssinaturaProfile, PagarAssinaturaViewModel e do PagarAssinaturaDTO
- Correção de PascalCase em IPagarAssinaturaService e PagarAssinaturaService
close #164
> Implementação do CSU004 - Pagar Assinatura - (2/3)

- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Avaliar/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Avaliar/Index.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Shared/_Layout.cshtml
Caso de uso Avaliar Profissional:
Implementar Views
Implementar Inicialização da Aplicação
close #179
> Implementar CSU012 - Avaliar Profissional (3/3)

- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/ContratacaoController.cs
- Codigo/AjudAkiWeb/AjudAkiWebTests/Controllers/ContratacaoControllerTests.cs
- Codigo/AjudAkiWeb/AjudAkiWebTests/Controllers/ServicoControllerTests.cs
- Codigo/AjudAkiWeb/Core/AjudakiContext.cs
- Codigo/AjudAkiWeb/ServiceTests/ContratacaoServiceTests.cs
- Codigo/AjudAkiWeb/ServiceTests/ServiceTests.csproj
- Ajusta nomenclatura da data nos testes de serviço.
- Retira código morto no AjudakiContext.
Close #171
> Implementa CSU01 - Testes do Contratar Serviço

- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/PagarAssinaturaController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/PagarAssinaturaViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Program.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/PagarAssinatura/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/PagarAssinatura/Delete.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/PagarAssinatura/Details.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/PagarAssinatura/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/PagarAssinatura/Index.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Shared/_Layout.cshtml
- Codigo/AjudAkiWeb/Service/PagarAssinaturaService.cs
Implementação do PagarAssinaturaController, Views e Inicialização da Aplicação
close #185
> Implementação do CSU004 - Pagar Assinatura - (3/3)

- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/AvaliarController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Program.cs
- Codigo/AjudAkiWeb/AjudAkiWebTests/Controllers/AvaliarControllerTests.cs
- Codigo/AjudAkiWeb/Core/Service/IAvaliarService.cs
- Codigo/AjudAkiWeb/Service/AvaliarService.cs
- Codigo/AjudAkiWeb/ServiceTests/AvaliarServiceTests.cs
Implementar teste do Controller.
Implementar teste do Service.
close #183
> Implementar CSU012 - Testes do Avaliar Profissional

- Codigo/AjudAkiWeb/AjudAkiWeb/Models/ClienteViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/ProfissionalViewModel.cs
- Codigo/AjudAkiWeb/Core/Core.csproj
- Codigo/AjudAkiWeb/Core/Dto/ClienteDTO.cs
- Codigo/AjudAkiWeb/Core/Service/IClienteService.cs
- Codigo/AjudAkiWeb/Service/ClienteService.cs
- Ajusta class para public class no PagarAssinaturaDTO.
- Ajusta nomenclatura do TipoPessoaEnum em ProfissionalViewModel.
Close #172
> Implementa CSU02 - ClienteDTO

- Codigo/AjudAkiWeb/AjudAkiWeb/Models/ServicoViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWebTests/Controllers/AgendaControllerTests.cs
- Codigo/AjudAkiWeb/AjudAkiWebTests/Controllers/AreaAtuacaoControllerTests.cs
- Codigo/AjudAkiWeb/Service/AgendaService.cs
- Codigo/AjudAkiWeb/Service/ServicoService.cs
- Codigo/AjudAkiWeb/ServiceTests/AgendaServiceTests.cs
- Codigo/AjudAkiWeb/ServiceTests/AreaAtuacaoServiceTests.cs
- Codigo/AjudAkiWeb/ServiceTests/ContratacaoServiceTests.cs
Correções extras adicionadas!
close #176
> Implementar Testes do CSU006 - Manter agenda 

- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/ServicoController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/TipoServicoController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Servico/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Servico/Delete.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Servico/Details.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Servico/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Servico/Index.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/TipoServico/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/TipoServico/Delete.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/TipoServico/Details.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/TipoServico/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/TipoServico/Index.cshtml
Recriado as views de serviço e modificado a controller de serviço, feito TipoServicoController.cs e as suas views,
> Implementar CSU011 - Manter tipos de Serviço (3/3)

- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Avaliar/Details.cshtml
Caso de Uso Avaliar Profissional:
Implementar View (Details)
> Correção do CSU012 - Avaliar Profissional

- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/AvaliarController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/ClienteController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/ClienteViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Cliente/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Cliente/Delete.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Cliente/Details.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Cliente/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Cliente/Index.cshtml
- Codigo/AjudAkiWeb/Core/Dto/ClienteDTO.cs
- Codigo/AjudAkiWeb/Service/ClienteService.cs
> Corrige as falhas em foreign key e no ENUM

- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/ClienteController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/ClienteViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Cliente/Create.cshtml
> CSU002 Manter cliente - Corrige as falhas no ENUM

- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/ProfissionalController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/ProfissionalViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Profissional/Create.cshtml
> CSU008 Manter Profissional - Corrigir as falhas no ENUM

- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/AvaliarController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/ProfissionalController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/AvaliarViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Avaliar/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Avaliar/Details.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Avaliar/Index.cshtml
Foi alterado o tipo de bool para sbyte no AvaliarViewModel
Foi gerado as Views novamente
close #218
> CSU012 Avaliar Profissional - Corrigir as falhas em foreign key

- Codigo/AjudAkiWeb/AjudAkiWeb/Models/AgendaViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/AssinaturaViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/AvaliarViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/ClienteViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/PagarAssinaturaViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/ProfissionalViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/ServicoViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/SolicitacaoServicoViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWebTests/Controllers/AvaliarControllerTests.cs
- Codigo/AjudAkiWeb/AjudAkiWebTests/Controllers/PagarAssinaturaControllerTests.cs
- Codigo/AjudAkiWeb/ServiceTests/AgendaServiceTests.cs
- Codigo/AjudAkiWeb/ServiceTests/AvaliarServiceTests.cs
- Codigo/AjudAkiWeb/ServiceTests/PagarAssinaturaServiceTests.cs
- Codigo/AjudAkiWeb/ServiceTests/ProfissionalServiceTests.cs
- Codigo/AjudAkiWeb/ServiceTests/TipoServicoServiceTests.cs
> Correções de bugs e atualizações de acordo com o BD

- Codigo/AjudAkiWeb/AjudAkiWeb/Models/AgendaViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/ClienteViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/ProfissionalViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/ServicoViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/SolicitacaoServicoViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Agenda/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Cliente/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Profissional/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Servico/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/SolicitacaoServico/Edit.cshtml
Caso de uso Serviço, profissional, cliente, Solicitação Serviço e agenda.
close #225
> Corrigir erros de "mês" nos casos necessários

- Codigo/AjudAkiWeb/AjudAkiWeb/Models/AssinaturaViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Cliente/Details.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Cliente/Index.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Contratacao/Details.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Contratacao/Index.cshtml
- Codigo/AjudAkiWeb/AjudAkiWebTests/Controllers/AssinaturaControllerTests.cs
- Codigo/AjudAkiWeb/AjudAkiWebTests/Controllers/AvaliarControllerTests.cs
- Codigo/AjudAkiWeb/AjudAkiWebTests/Controllers/ClienteControllerTests.cs
- Codigo/AjudAkiWeb/AjudAkiWebTests/Controllers/ContratacaoControllerTests.cs
- Codigo/AjudAkiWeb/AjudAkiWebTests/Controllers/PagarAssinaturaControllerTests.cs
- Codigo/AjudAkiWeb/AjudAkiWebTests/Controllers/ProfissionalControllerTests.cs
- Codigo/AjudAkiWeb/ServiceTests/AssinaturaServiceTests.cs
- Codigo/AjudAkiWeb/ServiceTests/ServiceTests.csproj
- Views de details e index de Manter Cliente e Contratar Serviço.
- Ajusta erros nos testes.
Close #227
> Ajusta testes quebrados e referencia ids nas views

- Codigo/AjudAkiWeb/AjudAkiWeb/Models/SolicitacaoServicoViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/SolicitacaoServico/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/SolicitacaoServico/Delete.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/SolicitacaoServico/Details.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/SolicitacaoServico/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/SolicitacaoServico/Index.cshtml
- Codigo/AjudAkiWeb/AjudAkiWebTests/Controllers/SolicitacaoServicoControllerTests.cs
- Codigo/AjudAkiWeb/ServiceTests/AreaAtuacaoServiceTests.cs
- Codigo/AjudAkiWeb/ServiceTests/SolicitacaoServicoServiceTests.cs
> Testes de mater Solicitação Serviço

- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/AssinaturaController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/AssinaturaViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Assinatura/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Assinatura/Delete.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Assinatura/Details.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Assinatura/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Assinatura/Index.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Avaliar/Index.cshtml
> Corrige ENUM de Assinatura

- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/ContratacaoController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/SolicitacaoServicoController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Models/SolicitacaoServicoViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWebTests/Controllers/SolicitacaoServicoControllerTests.cs
> CSU005 Manter solicitações de serviços - Atualizar Controller e View's com as foreign key

- Codigo/AjudAkiWeb/AjudAkiWeb/Models/AvaliarViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Assinatura/Create.cshtml
> Corrige erros de Assinatura e Avaliar

- Codigo/AjudAkiWeb/AjudAkiWeb/AjudAkiWeb.csproj
- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/AssinaturaController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/PagarAssinaturaController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Assinatura/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Assinatura/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Assinatura/Index.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Home/Index.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/PagarAssinatura/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Shared/_Layout.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/wwwroot/css/AssinaturaIndex.css
- Codigo/AjudAkiWeb/AjudAkiWeb/wwwroot/css/HomeIndex.css
- Criado parcialmente o Design System do Index de Manter Assinatura;
- Criado parcialmente o Design System do Home;
- Correções nas Views de PagarAssinatura e Assinatura;
- Alterado minimamente a View de _Layout.cshtml
close #237
>  Criado parcialmente o Design System de Manter Assinatura

- Codigo/AjudAkiWeb/AjudAkiWeb/Areas/Identity/Data/UsuarioIdentity.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Areas/Identity/Pages/Account/Register.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Areas/Identity/Pages/Account/Register.cshtml.cs
- Adiciona atributos de Pessoa em Usuario Identity.
- Adiciona campos das views na Register.cshtml.cs.
- Cria o primeiro esqueleto da tela de cadastro da aplicação no Register.cs.
Close #243
> Cria Tela de Registro de Cliente (1/2)

- Codigo/AjudAkiWeb/AjudAkiWeb/Models/AssinaturaViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Assinatura/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Assinatura/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/wwwroot/css/AssinaturaIndex.css
- Codigo/AjudAkiWeb/AjudAkiWeb/wwwroot/css/assinaturaCreate.css
- Pequenas alterações na tela Index de Assinatura.
- Cria Tela Create e Edit de Assinatura
close #241
> Cria a tela de Assinatura (2/3)

- Codigo/AjudAkiWeb/AjudAkiAPI/AjudAkiAPI - Backup.csproj
- Codigo/AjudAkiWeb/AjudAkiAPI/AjudAkiAPI.csproj
- Codigo/AjudAkiWeb/AjudAkiAPI/AjudAkiAPI.http
- Codigo/AjudAkiWeb/AjudAkiAPI/Controllers/WeatherForecastController.cs
- Codigo/AjudAkiWeb/AjudAkiAPI/Mappers/SolicitacaoServicoProfile.cs
- Codigo/AjudAkiWeb/AjudAkiAPI/Models/SolicitacaoServicoViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiAPI/Program.cs
- Codigo/AjudAkiWeb/AjudAkiAPI/Properties/launchSettings.json
- Codigo/AjudAkiWeb/AjudAkiAPI/WeatherForecast.cs
- Codigo/AjudAkiWeb/AjudAkiAPI/appsettings.Development.json
- Codigo/AjudAkiWeb/AjudAkiAPI/appsettings.json
- Codigo/AjudAkiWeb/AjudAkiWeb.sln
> Criação e configuração do ProjetoAPI

- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Shared/_Layout.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/wwwroot/css/colors.css
- Codigo/AjudAkiWeb/AjudAkiWeb/wwwroot/css/site.css
- Cria navbar da aplicação.
Close #250
> Cria tela de meu cadastro (1/3)

- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/SolicitacaoServicoController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/SolicitacaoServico/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/SolicitacaoServico/Edit.cshtml
> Correção de Solicitação Serviço

- Codigo/AjudAkiWeb/AjudAkiWeb/Models/AgendaViewModel.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Agenda/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Agenda/Index.cshtml
Tipo bool funcionando e selecionável
close #265
> Atualização do código da Agenda

- Codigo/AjudAkiWeb/AjudAkiWebTests/Controllers/AvaliarControllerTests.cs
- Codigo/AjudAkiWeb/AjudAkiWebTests/Controllers/TipoServicoControllerTests.cs
> Correção dos testes de Avaliar e TipoServico

- Codigo/AjudAkiWeb/AjudAkiWeb/Views/SolicitacaoServico/Index.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/wwwroot/css/solicitacaoservico.css
> Tela básica da solicitação serviço

- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Assinatura/Index.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/wwwroot/css/AssinaturaIndex.css
- Codigo/AjudAkiWeb/AjudAkiWeb/wwwroot/css/assinaturaCreate.css
- Cria modal no "Index" para Assinatura "Delete".
- Pequenas alterações nos botões de Create e Edit.
close #264
> Cria modal no Assinatura "Index" para Assinatura "Delete"

- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Assinatura/Index.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/wwwroot/css/AssinaturaIndex.css
> Corrige erros dos botões "excluir" e "criar plano" em Assinatura/Index.

- Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/AgendaController.cs
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Agenda/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Agenda/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Home/Index.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Profissional/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/wwwroot/css/ContratacaoIndext.css
> Correção de Bugs

- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Assinatura/Create.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Assinatura/Edit.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/Views/Assinatura/Index.cshtml
- Codigo/AjudAkiWeb/AjudAkiWeb/wwwroot/css/AssinaturaIndex.css
- Codigo/AjudAkiWeb/AjudAkiWeb/wwwroot/css/assinaturaCreate.css
> Correção de bugs de Assinatura

- Testes/orientação.txt
> Criação da pasta "Testes"
